apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-azurefiles-pvc
  labels:
    app: nginx-azurefiles-pvc
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  replicas: 4
  selector:
    matchLabels:
      app: nginx-azurefiles-pvc
  template:
    metadata:
      name: nginx-azurefiles-pvc
      labels:
        app: nginx-azurefiles-pvc
    spec:
      containers:
      - image: docker.io/nginx:1.20
        name: nginx-azurefiles-pvc
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: azurefilespvc
      volumes:
      - name: azurefilespvc
        persistentVolumeClaim:
          claimName: azurefile
