apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-dp-nginx-pvc-files-dynamic
  labels:
    app: dp-nginx-pvc-files-dynamic
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  replicas: 4
  selector:
    matchLabels:
      app: dp-nginx-pvc-files-dynamic
  template:
    metadata:
      name: dp-nginx-pvc-files-dynamic
      labels:
        app: dp-nginx-pvc-files-dynamic
    spec:
      containers:
      - image: docker.io/nginx:1.20
        name: dp-nginx-pvc-files-dynamic
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: azurefilespvc
      volumes:
      - name: azurefilespvc
        persistentVolumeClaim:
          claimName: my-azurefile-dynamic
